plugins {
    id("java")
    id("io.qameta.allure") version "2.12.0"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    // ===================== JUnit 5 =====================
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // ===================== Selenium =====================
    implementation("org.seleniumhq.selenium:selenium-java:4.46.0")

    // ===================== REST Assured =====================
    testImplementation("io.rest-assured:rest-assured:5.5.6")

    // ===================== Другое =====================
    implementation("com.google.code.gson:gson:2.13.2")
    implementation("org.postgresql:postgresql:42.7.12")

    // ===================== Allure =====================
    testImplementation("io.qameta.allure:allure-junit5:2.24.0")
    implementation("io.qameta.allure:allure-java-commons:2.24.0")


    implementation("tools.jackson.core:jackson-databind:3.2.2")

    implementation("org.apache.kafka:kafka_2.13:4.2.1")
}

// ===================== ✅ ИСПРАВЛЕННЫЙ БЛОК ALLURE (Groovy) =====================
allure {
    version = "2.24.0"
    useJUnit5 {
        version = "2.24.0"
    }
}

tasks.test {
    useJUnitPlatform()

    // Если задана переменная TEST_GROUP — фильтруем по пакету
    def testGroup = System.getenv("TEST_GROUP")
    if (testGroup != null && !testGroup.isBlank()) {
        include "**/${testGroup}/**"
    }

    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
    maxParallelForks = 1
}